# Site
name: 'Original Recipes'
description: 'Original Recipes'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: '/originalrecipes'
disqus: 'Original Recipes'
email: 'vamsikrishna.kuppa@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Vamsi:
    name:                   Vamsi
    pinterest:              https://in.pinterest.com/
    avatar:                 /assets/images/avatar1.jpg
    bio:                    "Hi, I am Vamsi, the designer of Original Recipes"
    email:                  vamsikrishna.kuppa@gmail.com
    instagram:              https://instagram.com/imvamsikvn/

  Suma:
    name:                     Suma
    pinterest:                https://in.pinterest.com/
    avatar:                   /assets/images/avatar2.jpg
    bio:                      "Hi, I am Suma, the author of Original Recipes"
    email:                    sumavempathi@gmail.com
    instagram:                https://instagram.com/sumavempathi/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Vamsi
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]